apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    name: apg-dep-petstore-apigee
    namespace: apigee-apihub-demo
    title: Apigee Deployment Apigee X
    description: Apigee Deployment Apigee X of API petstore
    labels:
        apihub-gateway: apihub-google-cloud-apigee
    tags:
        - apihub
    links:
        - url: https://pantheon.corp.google.com/apigee/hub/apis/petstore/overview?project=apigee-apihub-demo
          title: API Hub
spec:
    type: Service
    lifecycle: unknown
    owner: Group:apigee-apihub-demo/apg-owner
    providesApis:
        - API:apigee-apihub-demo/apg-petstore
