apiVersion: backstage.io/v1alpha1
kind: API
metadata:
    name: apg-fauna-ostriches
    namespace: apigee-apihub-demo
    title: Apigee Fauna Ostriches API
    description: The Fauna Ostriches API allows users to manage a collection of ostriches.
    labels:
        apihub-business-unit: fauna
        apihub-lifecycle: production
        apihub-style: apihub-openapi
        apihub-target-users: public
        apihub-team: fauna-birds
        categories: birds
        provider: fauna
        source: generate-animal-apis
        updated: "2023-06-07"
    tags:
        - apihub
    links:
        - url: https://pantheon.corp.google.com/apigee/hub/apis/fauna-ostriches/overview?project=apigee-apihub-demo
          title: API Hub
spec:
    type: openapi
    lifecycle: production
    owner: unknown
    definition: |
        openapi: 3.0.0
        info:
          version: 1.0.0
          title: Fauna Ostriches API
        servers:
          - url: https://apigee-apihub-demo.github.io
        paths:
          /ostriches:
            get:
              summary: List all ostriches
              operationId: listOstriches
              tags:
                - ostriches
              parameters:
                - name: limit
                  in: query
                  description: How many ostriches to return at one time (max 100)
                  schema:
                    type: integer
                    format: int32
              responses:
                "200":
                  description: A paged array of ostriches
                  headers:
                    x-next:
                      description: A link to the next page of responses
                      schema:
                        type: string
                  content:
                    application/json:
                      schema:
                        $ref: '#/components/schemas/Ostriches'
                default:
                  description: unexpected error
                  content:
                    application/json:
                      schema:
                        $ref: '#/components/schemas/Error'
            post:
              summary: Create ostrich
              operationId: createOstrich
              tags:
                - ostriches
              responses:
                "201":
                  description: Null response
                default:
                  description: unexpected error
                  content:
                    application/json:
                      schema:
                        $ref: '#/components/schemas/Error'
          /ostriches/{ostrichId}:
            get:
              summary: Info for a specific ostrich
              operationId: getOstrich
              tags:
                - ostriches
              parameters:
                - name: ostrichId
                  in: path
                  description: The id of the ostrich to retrieve
                  required: true
                  schema:
                    type: string
              responses:
                "200":
                  description: Expected response to a valid request
                  content:
                    application/json:
                      schema:
                        $ref: '#/components/schemas/Ostrich'
                default:
                  description: unexpected error
                  content:
                    application/json:
                      schema:
                        $ref: '#/components/schemas/Error'
        components:
          schemas:
            Error:
              type: object
              required:
                - code
                - message
              properties:
                code:
                  type: integer
                  format: int32
                message:
                  type: string
            Ostrich:
              type: object
              required:
                - id
                - name
              properties:
                id:
                  type: integer
                  format: int64
                name:
                  type: string
                tag:
                  type: string
            Ostriches:
              type: array
              maxItems: 100
              items:
                $ref: '#/components/schemas/Ostrich'
