apiVersion: backstage.io/v1alpha1
kind: API
metadata:
    name: apg-fauna-quokkas
    namespace: apigee-apihub-demo
    title: Apigee Fauna Quokkas API
    description: The Fauna Quokkas API allows users to manage a collection of quokkas.
    labels:
        apihub-business-unit: fauna
        apihub-lifecycle: production
        apihub-style: apihub-openapi
        apihub-target-users: public
        apihub-team: fauna-marsupials
        categories: marsupials
        provider: fauna
        source: generate-animal-apis
        updated: "2023-06-07"
    tags:
        - apihub
    links:
        - url: https://pantheon.corp.google.com/apigee/hub/apis/fauna-quokkas/overview?project=apigee-apihub-demo
          title: API Hub
spec:
    type: openapi
    lifecycle: production
    owner: unknown
    definition: |
        openapi: 3.0.0
        info:
          version: 1.0.0
          title: Fauna Quokkas API
        servers:
          - url: https://apigee-apihub-demo.github.io
        paths:
          /quokkas:
            get:
              summary: List all quokkas
              operationId: listQuokkas
              tags:
                - quokkas
              parameters:
                - name: limit
                  in: query
                  description: How many quokkas to return at one time (max 100)
                  schema:
                    type: integer
                    format: int32
              responses:
                "200":
                  description: A paged array of quokkas
                  headers:
                    x-next:
                      description: A link to the next page of responses
                      schema:
                        type: string
                  content:
                    application/json:
                      schema:
                        $ref: '#/components/schemas/Quokkas'
                default:
                  description: unexpected error
                  content:
                    application/json:
                      schema:
                        $ref: '#/components/schemas/Error'
            post:
              summary: Create quokka
              operationId: createQuokka
              tags:
                - quokkas
              responses:
                "201":
                  description: Null response
                default:
                  description: unexpected error
                  content:
                    application/json:
                      schema:
                        $ref: '#/components/schemas/Error'
          /quokkas/{quokkaId}:
            get:
              summary: Info for a specific quokka
              operationId: getQuokka
              tags:
                - quokkas
              parameters:
                - name: quokkaId
                  in: path
                  description: The id of the quokka to retrieve
                  required: true
                  schema:
                    type: string
              responses:
                "200":
                  description: Expected response to a valid request
                  content:
                    application/json:
                      schema:
                        $ref: '#/components/schemas/Quokka'
                default:
                  description: unexpected error
                  content:
                    application/json:
                      schema:
                        $ref: '#/components/schemas/Error'
        components:
          schemas:
            Error:
              type: object
              required:
                - code
                - message
              properties:
                code:
                  type: integer
                  format: int32
                message:
                  type: string
            Quokka:
              type: object
              required:
                - id
                - name
              properties:
                id:
                  type: integer
                  format: int64
                name:
                  type: string
                tag:
                  type: string
            Quokkas:
              type: array
              maxItems: 100
              items:
                $ref: '#/components/schemas/Quokka'
